// packages/vue/src/components/ToolbarBtn.vue
<script setup lang="ts">
defineProps<{ active?: boolean }>()
</script>

<template>
  <button class="toolbar-btn" :class="{ 'toolbar-btn--active': active }">
    <slot />
  </button>
</template>

<style scoped>
.toolbar-btn {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 5px 10px;
  background: transparent;
  border: 0.5px solid var(--color-border-secondary);
  border-radius: 6px;
  font-size: 13px;
  cursor: pointer;
  color: var(--color-text-primary);
  font-family: inherit;
  white-space: nowrap;
}
.toolbar-btn--active { background: var(--color-background-secondary); }
</style>

// packages/react/src/components/ToolbarBtn.tsx
import type { ReactNode } from 'react'

export interface ToolbarBtnProps {
  onClick?: () => void
  active?: boolean
  children: ReactNode
  title?: string
}

export function ToolbarBtn({ onClick, active, children, title }: ToolbarBtnProps) {
  return (
    <button
      onClick={onClick}
      title={title}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        padding: '5px 10px',
        background: active ? 'var(--color-background-secondary)' : 'transparent',
        border: '0.5px solid var(--color-border-secondary)',
        borderRadius: 6,
        fontSize: 13,
        cursor: 'pointer',
        color: 'var(--color-text-primary)',
        fontFamily: 'inherit',
        whiteSpace: 'nowrap',
      }}
    >
      {children}
    </button>
  )
}
