// packages/react/src/DataTable.tsx
import { useState, type CSSProperties } from 'react'
import { useTableState } from './useTableState'
import { Dropdown } from './components/Dropdown'
import { ToolbarBtn } from './components/ToolbarBtn'
import type { ColumnDef, DataTableProps } from './types'

const S = {
  wrap: { fontFamily: 'inherit', fontSize: 14, color: 'var(--color-text-primary)' } as CSSProperties,
  toolbar: { display: 'flex', alignItems: 'center', gap: 8, padding: '12px 0', borderBottom: '0.5px solid var(--color-border-tertiary)', flexWrap: 'wrap' } as CSSProperties,
  stats: { marginLeft: 'auto', fontSize: 12, color: 'var(--color-text-secondary)' } as CSSProperties,
  tableWrap: { overflowX: 'auto', border: '0.5px solid var(--color-border-tertiary)', borderRadius: 8, marginTop: 12 } as CSSProperties,
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 } as CSSProperties,
  th: { padding: '8px 12px', textAlign: 'left', fontWeight: 500, fontSize: 12, background: 'var(--color-background-secondary)', color: 'var(--color-text-secondary)', borderBottom: '0.5px solid var(--color-border-tertiary)', whiteSpace: 'nowrap', userSelect: 'none', cursor: 'pointer' } as CSSProperties,
  td: { padding: '8px 12px', borderBottom: '0.5px solid var(--color-border-tertiary)', color: 'var(--color-text-primary)', verticalAlign: 'middle' } as CSSProperties,
  ddItem: { display: 'flex', alignItems: 'center', gap: 8, padding: '7px 14px', cursor: 'pointer', fontSize: 13, color: 'var(--color-text-primary)' } as CSSProperties,
  ddSection: { padding: '6px 14px 2px', fontSize: 11, color: 'var(--color-text-tertiary)', fontWeight: 500, letterSpacing: '0.05em', textTransform: 'uppercase' } as CSSProperties,
  chip: { display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px', background: 'var(--color-background-secondary)', border: '0.5px solid var(--color-border-secondary)', borderRadius: 12, fontSize: 12, color: 'var(--color-text-secondary)' } as CSSProperties,
  groupRow: { background: 'var(--color-background-secondary)', fontWeight: 500, fontSize: 12, color: 'var(--color-text-secondary)', cursor: 'pointer' } as CSSProperties,
  groupTd: { padding: '6px 12px', borderBottom: '0.5px solid var(--color-border-tertiary)' } as CSSProperties,
  clearBtn: { fontSize: 12, background: 'none', border: 'none', color: 'var(--color-text-secondary)', cursor: 'pointer', padding: 0 } as CSSProperties,
  rangeInput: { width: 80, padding: '3px 6px', fontSize: 12, border: '0.5px solid var(--color-border-secondary)', borderRadius: 4, fontFamily: 'inherit', background: 'transparent', color: 'inherit' } as CSSProperties,
}

function asRecord(row: object): Record<string, unknown> {
  return row as Record<string, unknown>
}

export function DataTable<TRow extends object>({
  data,
  columns,
  rowKey,
  defaultVisibleColumns,
  labels,
}: DataTableProps<TRow>) {
  const [openColsDD, setOpenColsDD] = useState(false)
  const [openSortDD, setOpenSortDD] = useState(false)
  const [openFilterDD, setOpenFilterDD] = useState(false)
  const [openGroupDD, setOpenGroupDD] = useState(false)

  const {
    visibleCols, sorts, filters, rangeFilters, groupBy, collapsedGroups,
    processedData, groupedData, activeColumns, stringValueMap, activeFilterCount, L,
    toggleColVisibility, toggleSort, toggleFilter, setRangeFilter,
    toggleGroup, toggleGroupCollapse, clearColumnFilter,
    clearSorts, clearFilters, clearGroups, clearAll,
    getSortIcon, getSortIndex,
  } = useTableState(data, columns, defaultVisibleColumns, labels)

  const numericFilterCols = columns.filter(c => c.type === 'number' && c.filterable !== false)
  const stringFilterCols = columns.filter(c => c.type !== 'number' && c.type !== 'date' && c.filterable !== false)
  const groupableCols = columns.filter(c => c.groupable === true)
  const hasActiveState = sorts.length > 0 || activeFilterCount > 0 || groupBy.length > 0

  const cellValue = (row: TRow, col: ColumnDef<TRow>) => {
    const v = asRecord(row)[col.key]
    if (col.render) return col.render(v, row)
    if (col.format) return col.format(v)
    return v != null ? String(v) : ''
  }

  return (
    <div style={S.wrap}>
      <div style={S.toolbar}>
        {/* Columns */}
        <Dropdown open={openColsDD} setOpen={setOpenColsDD} trigger={
          <ToolbarBtn active={openColsDD}>{L.columns}</ToolbarBtn>
        }>
          <div style={S.ddSection}>{L.columnsSection}</div>
          {columns.map(col => (
            <label key={col.key} style={{ ...S.ddItem, cursor: 'pointer' }}>
              <input type="checkbox" checked={visibleCols.has(col.key)}
                onChange={() => toggleColVisibility(col.key)} style={{ margin: 0 }} />
              {col.label}
            </label>
          ))}
        </Dropdown>

        {/* Sort */}
        <Dropdown open={openSortDD} setOpen={setOpenSortDD} trigger={
          <ToolbarBtn active={sorts.length > 0}>
            {L.sort}
            {sorts.length > 0 && <span style={{ ...S.chip, marginLeft: 2 }}>{sorts.length}</span>}
          </ToolbarBtn>
        }>
          <div style={S.ddSection}>{L.sortSection}</div>
          {columns.map(col => {
            const s = sorts.find(s => s.key === col.key)
            return (
              <div key={col.key} style={S.ddItem} onClick={() => toggleSort(col.key)}>
                <span style={{ width: 18, fontSize: 11, color: 'var(--color-text-tertiary)', fontWeight: 500 }}>
                  {s ? sorts.indexOf(s) + 1 : ''}
                </span>
                <span style={{ flex: 1 }}>{col.label}</span>
                <span style={{ fontSize: 15, color: s ? 'var(--color-text-primary)' : 'var(--color-border-secondary)' }}>
                  {getSortIcon(col.key)}
                </span>
              </div>
            )
          })}
          {sorts.length > 0 && (
            <div style={{ padding: '4px 14px 6px' }}>
              <button onClick={e => { e.stopPropagation(); clearSorts() }} style={S.clearBtn}>
                {L.clearSorts}
              </button>
            </div>
          )}
        </Dropdown>

        {/* Filter */}
        {(stringFilterCols.length > 0 || numericFilterCols.length > 0) && (
          <Dropdown open={openFilterDD} setOpen={setOpenFilterDD} trigger={
            <ToolbarBtn active={activeFilterCount > 0}>
              {L.filter}
              {activeFilterCount > 0 && <span style={{ ...S.chip, marginLeft: 2 }}>{activeFilterCount}</span>}
            </ToolbarBtn>
          }>
            <div style={{ maxHeight: 380, overflowY: 'auto', minWidth: 240 }}>
              {stringFilterCols.map(col => (
                <div key={col.key}>
                  <div style={S.ddSection}>{col.label}</div>
                  {(stringValueMap[col.key] ?? []).map(v => (
                    <label key={v} style={{ ...S.ddItem, cursor: 'pointer' }}>
                      <input type="checkbox" checked={filters[col.key]?.has(v) ?? false}
                        onChange={() => toggleFilter(col.key, v)} style={{ margin: 0 }} />
                      {col.renderFilterLabel ? col.renderFilterLabel(v) : v}
                    </label>
                  ))}
                </div>
              ))}
              {numericFilterCols.length > 0 && (
                <>
                  <div style={S.ddSection}>{L.numericRanges}</div>
                  {numericFilterCols.map(col => (
                    <div key={col.key} style={{ padding: '4px 14px 8px' }}>
                      <div style={{ fontSize: 12, marginBottom: 4, color: 'var(--color-text-secondary)' }}>{col.label}</div>
                      <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                        <input type="number" placeholder={L.min}
                          value={rangeFilters[col.key]?.min ?? ''}
                          onChange={e => setRangeFilter(col.key, 'min', e.target.value)}
                          style={S.rangeInput} />
                        <span style={{ color: 'var(--color-text-tertiary)', fontSize: 12 }}>–</span>
                        <input type="number" placeholder={L.max}
                          value={rangeFilters[col.key]?.max ?? ''}
                          onChange={e => setRangeFilter(col.key, 'max', e.target.value)}
                          style={S.rangeInput} />
                      </div>
                    </div>
                  ))}
                </>
              )}
              {activeFilterCount > 0 && (
                <div style={{ padding: '4px 14px 8px' }}>
                  <button onClick={clearFilters} style={S.clearBtn}>{L.clearFilters}</button>
                </div>
              )}
            </div>
          </Dropdown>
        )}

        {/* Group */}
        {groupableCols.length > 0 && (
          <Dropdown open={openGroupDD} setOpen={setOpenGroupDD} trigger={
            <ToolbarBtn active={groupBy.length > 0}>
              {L.group}
              {groupBy.length > 0 && <span style={{ ...S.chip, marginLeft: 2 }}>{groupBy.length}</span>}
            </ToolbarBtn>
          }>
            <div style={S.ddSection}>{L.groupSection}</div>
            {groupableCols.map(col => (
              <div key={col.key} style={S.ddItem} onClick={() => toggleGroup(col.key)}>
                <span style={{ width: 18, fontSize: 11, color: 'var(--color-text-tertiary)', fontWeight: 500 }}>
                  {groupBy.includes(col.key) ? groupBy.indexOf(col.key) + 1 : ''}
                </span>
                <span style={{ flex: 1 }}>{col.label}</span>
                {groupBy.includes(col.key) && <span>✓</span>}
              </div>
            ))}
            {groupBy.length > 0 && (
              <div style={{ padding: '4px 14px 6px' }}>
                <button onClick={e => { e.stopPropagation(); clearGroups() }} style={S.clearBtn}>
                  {L.clearGroups}
                </button>
              </div>
            )}
          </Dropdown>
        )}

        {hasActiveState && (
          <button onClick={clearAll} style={{ marginLeft: 4, padding: '5px 10px', background: 'none', border: '0.5px solid var(--color-border-secondary)', borderRadius: 6, fontSize: 12, cursor: 'pointer', color: 'var(--color-text-secondary)', fontFamily: 'inherit' }}>
            {L.clearAll}
          </button>
        )}

        <div style={S.stats}>
          {L.rowCount(processedData.length, data.length)}
          {groupBy.length > 0 && L.groupCount(groupedData.length)}
        </div>
      </div>

      {/* Active chips */}
      {hasActiveState && (
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', padding: '8px 0 0' }}>
          {sorts.map((s, i) => (
            <span key={s.key} style={S.chip}>
              {i + 1}. {columns.find(c => c.key === s.key)?.label} {s.dir === 'asc' ? '↑' : '↓'}
              <span onClick={() => toggleSort(s.key)} style={{ cursor: 'pointer', marginLeft: 2 }}>×</span>
            </span>
          ))}
          {Object.entries(filters).filter(([, v]) => v.size > 0).map(([key, vals]) => (
            <span key={key} style={{ ...S.chip, background: 'var(--color-background-info)', color: 'var(--color-text-info)', border: '0.5px solid var(--color-border-info)' }}>
              {columns.find(c => c.key === key)?.label}: {[...vals].join(', ')}
              <span onClick={() => clearColumnFilter(key)} style={{ cursor: 'pointer', marginLeft: 2 }}>×</span>
            </span>
          ))}
          {groupBy.map((key, i) => (
            <span key={key} style={{ ...S.chip, background: 'var(--color-background-warning)', color: 'var(--color-text-warning)', border: '0.5px solid var(--color-border-warning)' }}>
              {L.groupLabel(i + 1)}: {columns.find(c => c.key === key)?.label}
              <span onClick={() => toggleGroup(key)} style={{ cursor: 'pointer', marginLeft: 2 }}>×</span>
            </span>
          ))}
        </div>
      )}

      {/* Table */}
      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              {groupBy.length > 0 && <th style={{ ...S.th, width: 28, cursor: 'default' }} />}
              {activeColumns.map(col => {
                const sortIdx = getSortIndex(col.key)
                return (
                  <th key={col.key} style={{ ...S.th, width: col.width }} onClick={() => toggleSort(col.key)}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                      {col.label}
                      <span style={{ fontSize: 10, color: sortIdx ? 'var(--color-text-primary)' : 'var(--color-border-secondary)' }}>
                        {sortIdx ? `${sortIdx}${getSortIcon(col.key)}` : '↕'}
                      </span>
                    </span>
                  </th>
                )
              })}
            </tr>
          </thead>
          <tbody>
            {groupedData.map(({ key: gkey, rows }) => {
              const isCollapsed = gkey !== null && collapsedGroups.has(gkey)
              return [
                gkey !== null && (
                  <tr key={`g-${gkey}`} style={S.groupRow} onClick={() => toggleGroupCollapse(gkey)}>
                    <td style={{ ...S.groupTd, width: 28 }}>{isCollapsed ? '▶' : '▼'}</td>
                    <td colSpan={activeColumns.length} style={S.groupTd}>
                      {groupBy.map((g, i) => {
                        const col = columns.find(c => c.key === g)
                        return (
                          <span key={g}>
                            {i > 0 && <span style={{ margin: '0 4px', opacity: 0.4 }}>›</span>}
                            <span style={{ marginRight: 4, opacity: 0.6 }}>{col?.label}:</span>
                            {col ? cellValue(rows[0], col) : String(asRecord(rows[0])[g] ?? '')}
                          </span>
                        )
                      })}
                      <span style={{ marginLeft: 10, fontWeight: 400, opacity: 0.6 }}>
                        {L.rowsInGroup(rows.length)}
                      </span>
                    </td>
                  </tr>
                ),
                !isCollapsed && rows.map((row, ri) => (
                  <tr key={rowKey ? String(asRecord(row)[rowKey] ?? ri) : ri}
                    style={{ background: ri % 2 === 0 ? 'transparent' : 'var(--color-background-secondary)' }}>
                    {gkey !== null && <td style={{ ...S.td, width: 28 }} />}
                    {activeColumns.map(col => (
                      <td key={col.key} style={{ ...S.td, width: col.width }}>
                        {cellValue(row, col)}
                      </td>
                    ))}
                  </tr>
                )),
              ]
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// packages/vue/src/DataTable.vue
<script setup lang="ts" generic="TRow extends object">
import { computed, useSlots } from 'vue'
import { useTableState } from './useTableState'
import type { ColumnDef } from './types'
import type { DataTableLabels } from '@vates/flexi-table-core'
import Dropdown from './components/Dropdown.vue'
import ToolbarBtn from './components/ToolbarBtn.vue'

const props = withDefaults(defineProps<{
  data: TRow[]
  columns: ColumnDef<TRow>[]
  rowKey?: string
  defaultVisibleColumns?: string[]
  labels?: Partial<DataTableLabels>
}>(), { rowKey: 'id' })

const slots = useSlots()

const state = useTableState(
  () => props.data,
  () => props.columns,
  () => ({ defaultVisibleColumns: props.defaultVisibleColumns, labels: props.labels }),
)

const {
  visibleCols, sorts, filters, rangeFilters, groupBy, collapsedGroups,
  processedData, groupedData, activeColumns, stringValueMap, activeFilterCount, L,
  toggleColVisibility, toggleSort, toggleFilter, setRangeFilter, clearColumnFilter,
  toggleGroup, toggleGroupCollapse, clearSorts, clearFilters, clearGroups, clearAll,
  getSortIcon, getSortIndex,
} = state

const numericFilterCols = computed(() =>
  props.columns.filter(c => c.type === 'number' && c.filterable !== false),
)
const stringFilterCols = computed(() =>
  props.columns.filter(c => c.type !== 'number' && c.type !== 'date' && c.filterable !== false),
)
const groupableCols = computed(() => props.columns.filter(c => c.groupable === true))
const hasActiveState = computed(
  () => sorts.value.length > 0 || activeFilterCount.value > 0 || groupBy.value.length > 0,
)

function asRecord(row: object): Record<string, unknown> {
  return row as Record<string, unknown>
}

function cellText(row: TRow, col: ColumnDef<TRow>): string {
  const v = asRecord(row)[col.key]
  if (col.format) return col.format(v)
  return v != null ? String(v) : ''
}

function findCol(key: string): ColumnDef<TRow> | undefined {
  return props.columns.find(c => c.key === key)
}

function hasSlot(name: string): boolean {
  return !!slots[name]
}
</script>

<template>
  <div class="ft">
    <!-- ── Toolbar ── -->
    <div class="ft__toolbar">

      <!-- Columns -->
      <Dropdown>
        <template #trigger="{ open }">
          <ToolbarBtn :active="open">{{ L.columns }}</ToolbarBtn>
        </template>
        <div class="ft__dd-section">{{ L.columnsSection }}</div>
        <label v-for="col in columns" :key="col.key" class="ft__dd-item ft__dd-item--clickable">
          <input type="checkbox" :checked="visibleCols.has(col.key)"
            @change="toggleColVisibility(col.key)" />
          {{ col.label }}
        </label>
      </Dropdown>

      <!-- Sort -->
      <Dropdown>
        <template #trigger="{ open }">
          <ToolbarBtn :active="open || sorts.length > 0">
            {{ L.sort }}
            <span v-if="sorts.length > 0" class="ft__chip">{{ sorts.length }}</span>
          </ToolbarBtn>
        </template>
        <div class="ft__dd-section">{{ L.sortSection }}</div>
        <div v-for="col in columns" :key="col.key" class="ft__dd-item" @click="toggleSort(col.key)">
          <span class="ft__sort-idx">{{ getSortIndex(col.key) ?? '' }}</span>
          <span class="ft__flex1">{{ col.label }}</span>
          <span :style="{ color: getSortIndex(col.key) ? 'var(--color-text-primary)' : 'var(--color-border-secondary)' }">
            {{ getSortIcon(col.key) }}
          </span>
        </div>
        <div v-if="sorts.length > 0" class="ft__dd-footer">
          <button @click.stop="clearSorts">{{ L.clearSorts }}</button>
        </div>
      </Dropdown>

      <!-- Filter -->
      <Dropdown v-if="stringFilterCols.length > 0 || numericFilterCols.length > 0">
        <template #trigger="{ open }">
          <ToolbarBtn :active="open || activeFilterCount > 0">
            {{ L.filter }}
            <span v-if="activeFilterCount > 0" class="ft__chip">{{ activeFilterCount }}</span>
          </ToolbarBtn>
        </template>
        <div class="ft__dd-scroll">
          <template v-for="col in stringFilterCols" :key="col.key">
            <div class="ft__dd-section">{{ col.label }}</div>
            <label v-for="v in stringValueMap[col.key]" :key="v" class="ft__dd-item ft__dd-item--clickable">
              <input type="checkbox" :checked="filters[col.key]?.has(v) ?? false"
                @change="toggleFilter(col.key, v)" />
              <!--
                Slot #filter-{key} — custom label in the filter dropdown.
                Slot scope: { value: string }
                Falls back to the raw string value.
              -->
              <slot :name="`filter-${col.key}`" :value="v">{{ v }}</slot>
            </label>
          </template>
          <template v-if="numericFilterCols.length > 0">
            <div class="ft__dd-section">{{ L.numericRanges }}</div>
            <div v-for="col in numericFilterCols" :key="col.key" class="ft__range">
              <div class="ft__range-label">{{ col.label }}</div>
              <div class="ft__range-inputs">
                <input type="number" :placeholder="L.min"
                  :value="rangeFilters[col.key]?.min ?? ''"
                  @input="setRangeFilter(col.key, 'min', ($event.target as HTMLInputElement).value)"
                  class="ft__range-input" />
                <span class="ft__range-sep">–</span>
                <input type="number" :placeholder="L.max"
                  :value="rangeFilters[col.key]?.max ?? ''"
                  @input="setRangeFilter(col.key, 'max', ($event.target as HTMLInputElement).value)"
                  class="ft__range-input" />
              </div>
            </div>
          </template>
          <div v-if="activeFilterCount > 0" class="ft__dd-footer">
            <button @click="clearFilters">{{ L.clearFilters }}</button>
          </div>
        </div>
      </Dropdown>

      <!-- Group -->
      <Dropdown v-if="groupableCols.length > 0">
        <template #trigger="{ open }">
          <ToolbarBtn :active="open || groupBy.length > 0">
            {{ L.group }}
            <span v-if="groupBy.length > 0" class="ft__chip">{{ groupBy.length }}</span>
          </ToolbarBtn>
        </template>
        <div class="ft__dd-section">{{ L.groupSection }}</div>
        <div v-for="col in groupableCols" :key="col.key" class="ft__dd-item" @click="toggleGroup(col.key)">
          <span class="ft__sort-idx">{{ groupBy.includes(col.key) ? groupBy.indexOf(col.key) + 1 : '' }}</span>
          <span class="ft__flex1">{{ col.label }}</span>
          <span v-if="groupBy.includes(col.key)">✓</span>
        </div>
        <div v-if="groupBy.length > 0" class="ft__dd-footer">
          <button @click.stop="clearGroups">{{ L.clearGroups }}</button>
        </div>
      </Dropdown>

      <button v-if="hasActiveState" class="ft__clear-all" @click="clearAll">{{ L.clearAll }}</button>

      <div class="ft__stats">
        {{ L.rowCount(processedData.length, data.length) }}
        <template v-if="groupBy.length > 0">{{ L.groupCount(groupedData.length) }}</template>
      </div>
    </div>

    <!-- ── Active chips ── -->
    <div v-if="hasActiveState" class="ft__chips">
      <span v-for="(s, i) in sorts" :key="s.key" class="ft__chip">
        {{ i + 1 }}. {{ columns.find(c => c.key === s.key)?.label }}
        {{ s.dir === 'asc' ? '↑' : '↓' }}
        <span class="ft__chip-remove" @click="toggleSort(s.key)">×</span>
      </span>
      <template v-for="[key, vals] in Object.entries(filters)" :key="key">
        <span v-if="vals.size > 0" class="ft__chip ft__chip--info">
          {{ columns.find(c => c.key === key)?.label }}: {{ [...vals].join(', ') }}
          <span class="ft__chip-remove" @click="clearColumnFilter(key)">×</span>
        </span>
      </template>
      <span v-for="(key, i) in groupBy" :key="key" class="ft__chip ft__chip--warning">
        {{ L.groupLabel(i + 1) }}: {{ columns.find(c => c.key === key)?.label }}
        <span class="ft__chip-remove" @click="toggleGroup(key)">×</span>
      </span>
    </div>

    <!-- ── Table ── -->
    <div class="ft__table-wrap">
      <table class="ft__table">
        <thead>
          <tr>
            <th v-if="groupBy.length > 0" class="ft__th" style="width: 28px" />
            <th v-for="col in activeColumns" :key="col.key" class="ft__th"
              :style="{ width: col.width ? `${col.width}px` : undefined }"
              @click="toggleSort(col.key)">
              {{ col.label }}
              <span :style="{ fontSize: '10px', color: getSortIndex(col.key) ? 'var(--color-text-primary)' : 'var(--color-border-secondary)' }">
                {{ getSortIndex(col.key) ? `${getSortIndex(col.key)}${getSortIcon(col.key)}` : '↕' }}
              </span>
            </th>
          </tr>
        </thead>
        <tbody>
          <template v-for="group in groupedData" :key="group.key ?? '__root__'">

            <!-- Group header -->
            <tr v-if="group.key !== null" class="ft__group-row"
              @click="toggleGroupCollapse(group.key!)">
              <td class="ft__group-td">
                {{ collapsedGroups.has(group.key!) ? '▶' : '▼' }}
              </td>
              <td :colspan="activeColumns.length" class="ft__group-td">
                <template v-for="(g, i) in groupBy" :key="g">
                  <span v-if="i > 0" class="ft__group-sep">›</span>
                  <span class="ft__group-key-label">{{ findCol(g)?.label }}:</span>
                  <!--
                    Slot #group-{key} — custom rendering in the group header.
                    Slot scope: { value: unknown, row: TRow }
                    Falls back to format() or string coercion.
                  -->
                  <slot :name="`group-${g}`"
                    :value="asRecord(group.rows[0])[g]"
                    :row="group.rows[0]">
                    {{ findCol(g) ? cellText(group.rows[0], findCol(g)!) : String(asRecord(group.rows[0])[g] ?? '') }}
                  </slot>
                </template>
                <span class="ft__group-count">{{ L.rowsInGroup(group.rows.length) }}</span>
              </td>
            </tr>

            <!-- Data rows -->
            <template v-if="group.key === null || !collapsedGroups.has(group.key!)">
              <tr v-for="(row, ri) in group.rows"
                :key="(asRecord(row)[rowKey] as string | number) ?? ri"
                :class="{ 'ft__tr--stripe': ri % 2 !== 0 }">
                <td v-if="group.key !== null" class="ft__td" style="width: 28px" />
                <td v-for="col in activeColumns" :key="col.key" class="ft__td"
                  :style="{ width: col.width ? `${col.width}px` : undefined }">
                  <!--
                    Slot #cell-{key} — custom cell rendering.
                    Slot scope: { value: unknown, row: TRow }
                    Falls back to format() or string coercion.
                  -->
                  <slot v-if="hasSlot(`cell-${col.key}`)"
                    :name="`cell-${col.key}`"
                    :value="asRecord(row)[col.key]"
                    :row="row" />
                  <template v-else>{{ cellText(row, col) }}</template>
                </td>
              </tr>
            </template>

          </template>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.ft { font-family: inherit; font-size: 14px; color: var(--color-text-primary); }

/* Toolbar */
.ft__toolbar {
  display: flex; align-items: center; gap: 8px; padding: 12px 0;
  border-bottom: 0.5px solid var(--color-border-tertiary); flex-wrap: wrap;
}
.ft__stats { margin-left: auto; font-size: 12px; color: var(--color-text-secondary); }
.ft__clear-all {
  margin-left: 4px; padding: 5px 10px; background: none;
  border: 0.5px solid var(--color-border-secondary); border-radius: 6px;
  font-size: 12px; cursor: pointer; color: var(--color-text-secondary); font-family: inherit;
}

/* Dropdown internals */
.ft__dd-section {
  padding: 6px 14px 2px; font-size: 11px; color: var(--color-text-tertiary);
  font-weight: 500; letter-spacing: 0.05em; text-transform: uppercase;
}
.ft__dd-item {
  display: flex; align-items: center; gap: 8px; padding: 7px 14px;
  font-size: 13px; color: var(--color-text-primary);
}
.ft__dd-item--clickable { cursor: pointer; }
.ft__dd-scroll { max-height: 380px; overflow-y: auto; min-width: 240px; }
.ft__dd-footer { padding: 4px 14px 6px; }
.ft__dd-footer button {
  font-size: 12px; background: none; border: none;
  color: var(--color-text-secondary); cursor: pointer; padding: 0;
}
.ft__sort-idx { width: 18px; font-size: 11px; color: var(--color-text-tertiary); font-weight: 500; }
.ft__flex1 { flex: 1; }

/* Range filter */
.ft__range { padding: 4px 14px 8px; }
.ft__range-label { font-size: 12px; margin-bottom: 4px; color: var(--color-text-secondary); }
.ft__range-inputs { display: flex; gap: 6px; align-items: center; }
.ft__range-sep { font-size: 12px; color: var(--color-text-tertiary); }
.ft__range-input {
  width: 80px; padding: 3px 6px; font-size: 12px;
  border: 0.5px solid var(--color-border-secondary); border-radius: 4px;
  font-family: inherit; background: transparent; color: inherit;
}

/* Chips */
.ft__chips { display: flex; gap: 6px; flex-wrap: wrap; padding: 8px 0 0; }
.ft__chip {
  display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px;
  background: var(--color-background-secondary); border: 0.5px solid var(--color-border-secondary);
  border-radius: 12px; font-size: 12px; color: var(--color-text-secondary);
}
.ft__chip--info {
  background: var(--color-background-info); color: var(--color-text-info);
  border-color: var(--color-border-info);
}
.ft__chip--warning {
  background: var(--color-background-warning); color: var(--color-text-warning);
  border-color: var(--color-border-warning);
}
.ft__chip-remove { cursor: pointer; margin-left: 2px; }

/* Table */
.ft__table-wrap {
  overflow-x: auto; border: 0.5px solid var(--color-border-tertiary);
  border-radius: 8px; margin-top: 12px;
}
.ft__table { width: 100%; border-collapse: collapse; font-size: 13px; }
.ft__th {
  padding: 8px 12px; text-align: left; font-weight: 500; font-size: 12px;
  background: var(--color-background-secondary); color: var(--color-text-secondary);
  border-bottom: 0.5px solid var(--color-border-tertiary); white-space: nowrap;
  user-select: none; cursor: pointer;
}
.ft__td {
  padding: 8px 12px; border-bottom: 0.5px solid var(--color-border-tertiary);
  color: var(--color-text-primary); vertical-align: middle;
}
.ft__tr--stripe { background: var(--color-background-secondary); }

/* Group rows */
.ft__group-row {
  background: var(--color-background-secondary); font-weight: 500; font-size: 12px;
  color: var(--color-text-secondary); cursor: pointer;
}
.ft__group-td { padding: 6px 12px; border-bottom: 0.5px solid var(--color-border-tertiary); }
.ft__group-sep { margin: 0 4px; opacity: 0.4; }
.ft__group-key-label { margin-right: 4px; opacity: 0.6; }
.ft__group-count { margin-left: 10px; font-weight: 400; opacity: 0.6; }
</style>
