// packages/react/src/components/ScoreBar.tsx
export interface ScoreBarProps {
  value: number
  max?: number
  /** Custom color thresholds as [minPct, color] pairs, sorted ascending by minPct */
  thresholds?: Array<[number, string]>
}

const DEFAULT_THRESHOLDS: Array<[number, string]> = [
  [90, '#3B6D11'],
  [75, '#185FA5'],
  [0, '#A32D2D'],
]

function resolveColor(pct: number, thresholds: Array<[number, string]>): string {
  for (const [min, color] of thresholds) {
    if (pct >= min) return color
  }
  return thresholds[thresholds.length - 1][1]
}

export function ScoreBar({ value, max = 100, thresholds = DEFAULT_THRESHOLDS }: ScoreBarProps) {
  const pct = Math.min(100, Math.max(0, (value / max) * 100))
  const color = resolveColor(pct, thresholds)
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
      <div
        style={{
          flex: 1,
          height: 6,
          background: '#F1EFE8',
          borderRadius: 3,
          overflow: 'hidden',
        }}
      >
        <div
          style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: 3 }}
        />
      </div>
      <span style={{ fontSize: 12, minWidth: 26, color }}>{value}</span>
    </div>
  )
}

// packages/vue/src/components/ScoreBar.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  value: number
  max?: number
}>(), { max: 100 })

const pct = computed(() => Math.min(100, Math.max(0, (props.value / props.max) * 100)))
const color = computed(() => pct.value >= 90 ? '#3B6D11' : pct.value >= 75 ? '#185FA5' : '#A32D2D')
</script>

<template>
  <div class="score-bar">
    <div class="score-bar__track">
      <div class="score-bar__fill" :style="{ width: `${pct}%`, background: color }" />
    </div>
    <span class="score-bar__label" :style="{ color }">{{ value }}</span>
  </div>
</template>

<style scoped>
.score-bar { display: flex; align-items: center; gap: 6px; }
.score-bar__track { flex: 1; height: 6px; background: #F1EFE8; border-radius: 3px; overflow: hidden; }
.score-bar__fill { height: 100%; border-radius: 3px; }
.score-bar__label { font-size: 12px; min-width: 26px; }
</style>
